name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: texlive/texlive:latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Debug repository files
      - name: Debug repository files
        run: |
          echo "Root directory contents:"
          ls -la
          echo "Searching for CV.tex and info.txt:"
          find . -name 'CV.tex'
          find . -name 'info.txt'

      # Step 3: Install prerequisites
      - name: Install prerequisites
        run: |
          apt-get update && apt-get install -y poppler-utils pdftk

      # Step 4: Compile CV.tex to PDF
      - name: Compile CV.tex to PDF
        run: |
          mkdir -p output
          pdflatex -interaction=nonstopmode -halt-on-error -file-line-error -output-directory=output CV.tex
          echo "Output directory contents:"
          ls -la output

      # Step 5: Apply metadata from info.txt
      - name: Apply metadata to PDF
        run: |
          if [ -f output/CV.pdf ] && [ -f info.txt ]; then
            echo "Applying metadata from info.txt to CV.pdf..."
            pdftk output/CV.pdf update_info_utf8 info.txt output output/CV_with_metadata.pdf
            mv output/CV_with_metadata.pdf output/CV.pdf
          else
            echo "PDF or info.txt file is missing. Skipping metadata application."
          fi

      # Step 6: Copy the output to the root directory
      - name: Copy generated PDF
        run: |
          echo "Contents of current directory:"
          ls -la
          echo "Contents of output directory:"
          ls -la output/
          mv -f output/CV.pdf ./CV.pdf
          echo "Contents after move:"
          ls -la CV.pdf

      # Step 7: Debug final PDF
      - name: Debug final PDF
        run: |
          echo "Final PDF details:"
          ls -lh CV.pdf
          test -f CV.pdf && echo "PDF exists" || echo "PDF does not exist"
